"""add synopsis to books

Revision ID: ca883df3f8a5
Revises: 1ba646289ba0
Create Date: 2026-05-18 12:32:17.564546

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ca883df3f8a5"
down_revision: str | Sequence[str] | None = "1ba646289ba0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("synopsis", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "synopsis")
    # ### end Alembic commands ###
